---
title: "Econ 448"
subtitle: "Problem Set 2"
author: Melissa Knox
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: html_notebook  
---
## Concept Questions

You can submit your answers to these in a separate document from the data questions below or you can use markdown to write equations using similar syntax to LaTex.  (c.f. https://rmd4sci.njtierney.com/math)

1. A household derives utility from the number of children n and consumption c according to the utility function
$U(z,n)=z^α n^β$    (where $α+β=1$)
The income of the household is Y and the price of children is pn. With the price of consumption set equal to one the household’s budget constraint is
$I=p_n n+p_z z$

1.1 Calculate the utility maximizing demand for children as a function of income and      prices. How does the demand for children change as I increases in this model? How         would the demand for children change as preferences for children increase (that is,       as β gets larger)?

Now replace I with $Y+L*w$, where Y is male income, $L*w$ is female wage income, and $L=T-k*n$.  T is the total number of hours in the day and $k*n$ is the total amount of time that women spend raising their n children.  

  1.2 Rearrange terms to get a new price of children, $p_n^*$, which includes both explicit     and opportunity costs of children.  How does this price vary with the woman’s wage?
	  Now find the household’s demand for children as a function of this new price, $p_n^*$.     (Hint: You may substitute $p_n^*$ for $p_n$ and $Y+Tw$ for I if you don’t want to           explicitly re-solve the problem.)  How does the demand for children vary with w now?      Why do we say that the effect of a female wage increase on fertility is ambiguous?

2. Why would an estimate of the effect of contraceptive use on a woman's fertility potentially be biased?  How does Miller use a natural experiment to remove this bias?  In your answer, define the natural experiment and discuss how the natural experiment satisfies the "exclusion restriction" for the bias you described in the first part of this question. 

## Data Analysis Questions
3. These questions refer to the data set "1% sample Botswana ever-married women age 15+" available via the Econ 448 class account from ipums.org (class code is 9JIY6C).  Please create an account, download the data and answer the following questions.

3.1 Create a formatted table of summary statistics (mean, std dev, max, min) for all variables that you use in your analysis (Hint: wait until you answer all of the other questions before finalizing this part so you know what variables you will use).

3.2 Plot mean number of children against years of education. What relationship do you see between these data and what does that tell you about what output you would expect from a regression?

3.3 Using the main data frame, use ordinary least squares to estimate the coefficient $\beta_1$ in the regression model $Y_i=\beta_0+\beta_1X_i+\epsilon_i$, where Y is children ever born and X is a woman's education.  Show your results. Does the sign match what you expect to see? Note: Typically, we might transform the data, perhaps by taking the log of children, or use a non-linear regression such as a Poisson regression here.  However, the zeros make this a little more complicated.   

3.4 Now let's add some control variables.  Choose at least two control variables from the available variables in the data.  What variables did you choose and what sign do you expect the coefficients on these variables to have? Why? 

3.5 Add these variables to your regression model from the previous question and display your results.  (Be careful that you understand the structure of the variables you have chosen and "clean" them as needed before including in your model.) Do the coefficients match your expectations?  Does the coefficient on education change once you add the control variables?
